### PR TITLE
Enhance Crypt::PK::DH

### PR DESCRIPTION
**Pull request by lkinley**
Here it is... Passes old tests plus the new ones.  100% backward compatible.

Let me know what you think.

### CODE REVIEW

**Comment by karel-m** [comment]
Looks good, very good indeed :+1:

I only want to suggest couple of tweaks to the chosen interface. My motivation is to keep `Crypt::PK::DH` more or less on the same track as for example `Crypt::PK::ECC`

Ad `generate_key` I would prefer `$dh->generate_key($param_hash)` which corresponds to `$ec->generate_key($curve_param_hash)` that we already have for ECC. - I would avoid `generate_key($g, $p)`.

So:
```perl
$dh->generate_key({g=>$g_hex, p=>$p_hex}) #new interface
#or
$dh->generate_key($size); #old interface
``` 

Considering a bit unclear origin of libtomcrypt built-in params mentioned in https://github.com/libtom/libtomcrypt/issues/114 I would suggest to offer `Crypt::PK::DH` users a new set of pre-defined DH params.

For example DH params from https://tools.ietf.org/html/rfc7296 and https://tools.ietf.org/html/rfc3526 Which can be used like this `$dh->generate_key('ike2048')` (again similar to ECC interface where you can also use some of the pre-defined curve names).

I mean simply hardcoding in `DH.pm` something like:
```
my %DH_PARAMS = {
  ike768  => { g => 2, p => 'FFFFFFFFFFFFFFFFC90FDAA22168C234C4C6628B80DC1CD1'.
                            '29024E088A67CC74020BBEA63B139B22514A08798E3404DD'.
                            'EF9519B3CD3A431B302B0A6DF25F14374FE1356D6D51C245'.
                            'E485B576625E7EC6F44C42E9A63A3620FFFFFFFFFFFFFFFF'
  },
  ike1024 => { g => 2, p => 'FFFFFFFFFFFFFFFFC90FDAA22168C234C4C6628B80DC1CD1'.
                            '29024E088A67CC74020BBEA63B139B22514A08798E3404DD'.
                            'EF9519B3CD3A431B302B0A6DF25F14374FE1356D6D51C245'.
                            'E485B576625E7EC6F44C42E9A637ED6B0BFF5CB6F406B7ED'.
                            'EE386BFB5A899FA5AE9F24117C4B1FE649286651ECE65381'.
                            'FFFFFFFFFFFFFFFF'
  },
  ike1536 => { g => 2, p => 'FFFFFFFFFFFFFFFFC90FDAA22168C234C4C6628B80DC1CD1'.
                            '29024E088A67CC74020BBEA63B139B22514A08798E3404DD'.
                            'EF9519B3CD3A431B302B0A6DF25F14374FE1356D6D51C245'.
                            'E485B576625E7EC6F44C42E9A637ED6B0BFF5CB6F406B7ED'.
                            'EE386BFB5A899FA5AE9F24117C4B1FE649286651ECE45B3D'.
                            'C2007CB8A163BF0598DA48361C55D39A69163FA8FD24CF5F'.
                            '83655D23DCA3AD961C62F356208552BB9ED529077096966D'.
                            '670C354E4ABC9804F1746C08CA237327FFFFFFFFFFFFFFFF'
  },
  # ...
};
```

The next comment I have is related to `$dh->public_key()` method which I would like to be called rather `$dh->export_key_raw('public')` which is again similar to the interface in ECC. Which brings a question whether it might be useful to also have something like `$dh->import_key_raw` - It might need some params like: `$dh->import_key_raw($raw_pubkey, {g=>$g, p=>$p})`. And to make it a complete analogy to ECC perhaps also `$dh->params2hash` so that you can use:
```perl
$dh_private = ... somehow loaded/generated ...
$dh_public = Crypt::PK::DH->new->import_key_raw($raw_pubkey, $dh_private->params2hash)
#or if you use pre-defined DH group
$dh_public = Crypt::PK::DH->new->import_key_raw($raw_pubkey, 'ike2048')
```

As for supporting `shared_secret($raw_pubkey_hex)` and `is_pubkey_valid` I see want you want to achieve but I do not have my opinion yet :)

**Comment by karel-m** [comment]
Some more thoughts.

We might want to support:
* `$raw_bytes = $dh->export_key_raw('public')`
* `$raw_bytes = $dh->export_key_raw('private')`
* during `import` we will not be able to distinguish whether raw bytes are private or public key so an extra param will be needed
* `$dh->import_key_raw($raw_bytes, 'public', { g=>$g, p=>$p})`
* `$dh->import_key_raw($raw_bytes, 'public', 'ike2048')`
* `$dh->import_key_raw($raw_bytes, 'private', { g=>$g, p=>$p})`
* `$dh->import_key_raw($raw_bytes, 'private', 'ike2048')`

And ss for the DH's `key2hash` method I would suggest not exporting `name` value as it is now more or less useless (at least when not using the old libtomcrypt predefined DH groups).

**Comment by karel-m** [comment]
And the rest of my feedback

1/ You suggest shared_secret accepting hex string:
```
$secret = $priv->shared_secret($pub_hex);
```

Which is basically a short cut for the following:
```
$pub = Crypt::PK::DH->new->import_key_raw(pack("H*", $pub_hex), 'public', $priv->params2hash);
$secret = $priv->shared_secret($pub);
```
I know, it's a bit more complicated but IMO a cleaner interface.

2/ You suggest `is_pubkey_valid` method:

I would rather see `is_pubkey_valid` as a private method and `import_key_raw($pub_bytes, 'public', $dh_params)` calling this method behind the scene and simply not allowing loading invalid public keys.


3/ I suggest (as mentioned above) adding:
```
$dh->params2hash();  # returns { g=>"hex_number", p=>"hex_number" }
```

**Comment by lkinley** [comment]
Excellent feedback.  I like your suggestions very much and once implemented will suit my needs very well.

In the work I am doing on Net::SSH::Perl I need the ability to get the (raw) public key in and out so your proposed methods are perfect.

I'll get these implemented.

**Comment by lkinley** [comment]
Let me know what you think of the latest commit.

**Pull request merged**
